### ISSUE TITLE
Minor typo -bp instead of -b

### ISSUE THREAD

**Issue by woctezuma** [UwUDev/balamod#10]
When I run the exe, I get a message mentioning `-bp` instead of `-b`:

```
C:\Users\Wok\AppData\Roaming\Balatro>balamod-v0.1.8-windows.exe -a
'C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf' not found.
No Balatro found!
Please specify the path to your Balatro installation with the -bp option
```

However, `-bp` does not work:

```
C:\Users\Wok\AppData\Roaming\Balatro>balamod-v0.1.8-windows.exe -a -bp C:\Applis\Steam\steamapps\common
error: unexpected argument 'C:\Applis\Steam\steamapps\common' found

Usage: balamod-v0.1.8-windows.exe [OPTIONS]

For more information, try '--help'.
```

The right CLI argument is `-b`, as mentioned in the README:

```
C:\Users\Wok\AppData\Roaming\Balatro>balamod-v0.1.8-windows.exe -a -b C:\Applis\Steam\steamapps\common\Balatro
'C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf' not found.
Implementing modloader on main...
Implementing modloader on uidef...
Done!
Injecting main
Done!
Injecting uidef
Done!
Total time: 12.7500204s
Modloader implementation (main): 17.9495ms
Modloader implementation (uidef): 1.693ms
Modloader injection (main): 5.7343235s
Modloader injection (uidef): 6.9845138s
```

I think the issue stems from the long argument name `balatro-path`, which seems to be printed in the error message as `bp` instead of the short argument name `b`.

https://github.com/UwUDev/balamod/blob/fdb2c5dca5958f6e418455b708a88f2716844254/src/main.rs#L23-L24

**Comment by UwUDev** [comment]
Ty, also vdf detection has been fixed https://github.com/UwUDev/balamod/commit/4c446244642588c956983c8489fb009a52956f2e

**Comment by UwUDev** [comment]
I forgot that I already fixed the typo https://github.com/UwUDev/balamod/commit/8547224f677b3fb0f07e9bfc496aaabc69c95caa

**Comment by woctezuma** [comment]
Ahah, I see! I was using the latest release, but it is 2 weeks old!

**Comment by UwUDev** [comment]
Yeah, I'll try to release 0.1.9 soon, I just need te fix the new mod menu UI and we're good
