### ISSUE TITLE
discord server expansion

### ISSUE THREAD

**Issue by NielsCloer** [UwUDev/balamod#30]
The discord server for the community is currently rather barebones, adding channels that might seem like they would die within a week and seeing if there is an interest could be a good way to get people more interested.
To this end a "suggestions" channel that is strictly directed towards adding things to the discord would be a good addition to then pull from for additions to the server.
If suggestions are taken from there they can easily be removed again if no interest is taken.

**Comment by UwUDev** [comment]
Please keep the issues only related to the repo, it's completely off topic. I'd be happy to talk about it on discord but this GitHub isn't the place for that
