### ISSUE TITLE
Information on balamod seems scattered

### ISSUE THREAD

**Issue by NielsCloer** [UwUDev/balamod#31]
The information needed to get started on modding balatro is placed in the place where most people trying to figure it out on there own will find but as modding communities are often people's starting point into programming and therefore git/github they'll inevitably be lost looking around a discord server that isnt set up to support them.
While this might seem fine at first glance since those people could be assumed to be unlikely to contribute in substantial measures to any projects it still seems worthwhile to me to at least put the basics (like a readme channel or an FAQ channel) in place for those people to find there footing. With any luck this will be the encouragement some need to actually get into things properly.

**Comment by UwUDev** [comment]
https://github.com/balamod/balamod.github.io
https://balamod.github.io/docs/user-guide/faq (unfinished)
https://github.com/UwUDev/balamod/issues/30#issuecomment-2015755491

Please come on discord to talk about it
