### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by sbordeyne** [UwUDev/balamod#7]
Balatro recently updated to add MacOS support. The process to patch the game is very similar to the windows version too, so it should be pretty straightforward to implement (unfortunately, I suck at Rust, so I can't offer a PR)

- Balatro path is in `~/Library/Application Support/Steam/steamapps/common/Balatro/Balatro.app/Contents/Resources/Balatro.love`
- It's also just a plain ZIP archive, containing the same code as in the Windows version

You can open the aforementionned path like a regular path (MacOS App Bundles are treated as regular directories), instead of patching a file named "Balatro.exe"

**Comment by UwUDev** [comment]
The problem it that i don't have any machine that can run MacOS to test :/ 
if you have a mac, a pull request to add support on macOS would be greatly appreciated
