### ISSUE TITLE
Injections ignore the "%" symbol

### ISSUE THREAD

**Issue by Mysthaps** [UwUDev/balamod#9]
Applying a test patch:
```lua
local test = "this%is%a%test%string!"
```
to the function ``Card:set_card_area``, as an example, results in this:
```lua
function Card:set_card_area(area)
    local test = "thisisateststring!"

    self.area = area
    self.parent = area
    self.layered_parallax = area.layered_parallax
end
```

**Comment by UwUDev** [comment]
it's because % is for lua regexes, try to escape you whole patch with `:gsub("([^%w])"`

**Comment by UwUDev** [comment]
`:gsub("([^%w])", "%%%1")` my bad

**Comment by Mysthaps** [comment]
ah, so it was just some lua horrors i wasn't aware of, thanks! closing

**Comment by UwUDev** [comment]
if you want to read a bit about lua regexes https://www.lua.org/manual/5.1/manual.html#5.4.1
